"""DesignPlan v0.1 public API."""

from schematic_ai.domain.design_plan.enums import (
    ArchitectureDecisionStatus,
    ArchitectureDecisionType,
    ArchitectureChoice,
    ConnectionKind,
    FunctionalBlockStatus,
    FunctionalBlockType,
    FunctionalPortKind,
    FunctionalTopologyClass,
    InterfaceDirection,
    InterfaceType,
    MappingTargetType,
    OpenDecisionStatus,
    PortDirection,
    PowerDomainRole,
    RequirementMappingStatus,
)
from schematic_ai.domain.design_plan.models import (
    ArchitectureDecision,
    BlockConnection,
    ConnectionEndpoint,
    DesignAssumption,
    DesignPlan,
    DesignPlanMetadata,
    FunctionalBlock,
    FunctionalPort,
    Interface,
    MappingTarget,
    OpenArchitectureDecision,
    PowerDomain,
    RequirementMapping,
    SourceRequirementSet,
)
from schematic_ai.domain.design_plan.validation import (
    DesignPlanContextValidationError,
    validate_design_plan_against_requirements,
)

__all__ = [
    "ArchitectureDecision",
    "ArchitectureDecisionStatus",
    "ArchitectureDecisionType",
    "ArchitectureChoice",
    "BlockConnection",
    "ConnectionEndpoint",
    "ConnectionKind",
    "DesignAssumption",
    "DesignPlan",
    "DesignPlanContextValidationError",
    "DesignPlanMetadata",
    "FunctionalBlock",
    "FunctionalBlockStatus",
    "FunctionalBlockType",
    "FunctionalPort",
    "FunctionalPortKind",
    "FunctionalTopologyClass",
    "Interface",
    "InterfaceDirection",
    "InterfaceType",
    "MappingTarget",
    "MappingTargetType",
    "OpenArchitectureDecision",
    "OpenDecisionStatus",
    "PortDirection",
    "PowerDomain",
    "PowerDomainRole",
    "RequirementMapping",
    "RequirementMappingStatus",
    "SourceRequirementSet",
    "validate_design_plan_against_requirements",
]
