"""CircuitIR v0.1 public API."""

from schematic_ai.domain.circuit_ir.enums import (
    CircuitAssumptionStatus,
    CircuitComponentRole,
    ComponentResolutionStatus,
    ImplementationMappingType,
    ImplementationStatus,
    NetRole,
    OpenImplementationDecisionStatus,
    PinConnectionState,
    PinElectricalType,
    PinResolutionStatus,
)
from schematic_ai.domain.circuit_ir.models import (
    CircuitAssumption,
    CircuitGroup,
    CircuitIR,
    CircuitIRMetadata,
    CircuitInterfaceBinding,
    ComponentInstance,
    ComponentParameter,
    EnumCircuitValue,
    KnowledgeReference,
    Net,
    NetConnection,
    NetProperty,
    OpenImplementationDecision,
    PinInstance,
    QuantityCircuitValue,
    SourceDesignPlan,
    TextCircuitValue,
    BooleanCircuitValue,
    next_circuit_revision,
)
from schematic_ai.domain.circuit_ir.validation import (
    CircuitIRContextValidationError,
    design_plan_object_ids,
    validate_circuit_ir_against_design_plan,
    validate_circuit_ir_against_knowledge,
)

__all__ = [
    "BooleanCircuitValue",
    "CircuitAssumption",
    "CircuitAssumptionStatus",
    "CircuitComponentRole",
    "CircuitGroup",
    "CircuitIR",
    "CircuitIRContextValidationError",
    "CircuitIRMetadata",
    "CircuitInterfaceBinding",
    "ComponentInstance",
    "ComponentParameter",
    "ComponentResolutionStatus",
    "EnumCircuitValue",
    "ImplementationMappingType",
    "ImplementationStatus",
    "KnowledgeReference",
    "Net",
    "NetConnection",
    "NetProperty",
    "NetRole",
    "OpenImplementationDecision",
    "OpenImplementationDecisionStatus",
    "PinConnectionState",
    "PinElectricalType",
    "PinInstance",
    "PinResolutionStatus",
    "QuantityCircuitValue",
    "SourceDesignPlan",
    "TextCircuitValue",
    "design_plan_object_ids",
    "next_circuit_revision",
    "validate_circuit_ir_against_design_plan",
    "validate_circuit_ir_against_knowledge",
]
